### ISSUE TITLE
Unexpressible kitty / Xresources theme 

### ISSUE THREAD

**Issue by TannerYoung** [mjswensen/themer#44]
I can't express my current theme in the configuration provided:
Desired output:
```
# black
color0    #282828
color8    #928374

# red
color1    #cc241d
color9    #fb4934

# green
color2    #98971a
color10   #b8bb26

# yellow
color3    #d79921
color11   #fabd2f

# blue
color4    #458588
color12   #83a598

# magenta
color5    #b16286
color13   #d3869b

# cyan
color6    #689d6a
color14   #8ec07c

# white
color7    #a89984
color15   #ebdbb2
```

Closest configuration:
```
module.exports.colors = {
  "dark": {
    "shade0" : "#282828",
    "accent0": "#cc241d",
    "shade1" : "#928374",
    "accent1": "#fb4934",
    "shade2" : "#98971a",
    "accent2": "#b8bb26",
    "shade3" : "#d79921",
    "accent3": "#fabd2f",
    "shade4" : "#458588",
    "accent4": "#83a598",
    "shade5" : "#b16286",
    "accent5": "#d3869b",
    "shade6" : "#689d6a",
    "accent6": "#8ec07c",
    "shade7" : "#a89984",
    "accent7": "#ebdbb2"
  }
};
```

Result: (sorted for cleaner comparison)
```
# generated by themer-kitty
# dark variant of theme colors.js
foreground #689d6a
background #282828
color0 #282828
color8 #cc241d
color1 #928374
color9 #fb4934
color2 #fabd2f
color10 #83a598
color3 #b8bb26
color11 #b8bb26
color4 #d3869b
color12 #d3869b
color5 #ebdbb2
color13 #ebdbb2
color6 #83a598
color14 #83a598
color7 #689d6a
color15 #a89984
```

This doesn't allow using the bolded accent colors for terminals as far as I can tell. Is there something I'm doing wrong?

**Comment by mjswensen** [comment]
I think what's happening here is the mapping of colors in [themer-kitty](https://www.npmjs.com/package/themer-kitty) is not lining up with what you'd expect.

This is a community-contributed package, but the [original repo](https://github.com/0x52a1/themer-kitty) backing the npm package is gone—I'll need to add a new, officially supported version so that we can fine-tune the color mappings from there.

As for the colors, the approach taken over in [themer-alacritty's template](https://github.com/mjswensen/themer/blob/master/cli/packages/themer-alacritty/lib/index.js) is to mathematically brighten or dim the source accent colors, which I think would work well here.

**Comment by mjswensen** [comment]
Will get to this as soon as I get a chance!

**Comment by mjswensen** [comment]
OK, I've released an officially supported version at `@themer/kitty` on npm, as well as deployed it to the web UI in lieu of the community-contributed module. It's got some additional properties that the original didn't have, as well.

Give it a try, @TannerYoung , and feel free to log another issue if anything looks incorrect.
