### ISSUE TITLE
Feature: Display what shades and accents  that will be mapped to the colors for a theme

### ISSUE THREAD

**Issue by simonljus** [mjswensen/themer#7]
I have tried out Themer for a few hours and I tried to make a new color scheme for Sublime Text. I had some problem figuring out which accents and shades were used for what in Sublime. I tried to view it manually later but it would be great if it was possible to see it directly in the app when customizing a theme.  The mappings could be viewed under a menu or something.

**Comment by mjswensen** [comment]
This makes a lot of sense, @simonljus . I had actually had something similar at one point, but ended up taking it out. 😑 I will dig it out of the git history and put it back in under a menu option, as you suggested.

I'll close this for now and create an issue over on [themer-gui](https://github.com/mjswensen/themer-gui) since technically that's where this feature will go.
